name: whois-snap
version: '0.1'
summary: whois snap
description: |
    whois snap
grade: stable
confinement: strict

parts:
  archives:
    plugin: nil
    stage-packages:
      - whois
  env:
    plugin: dump
    organize:
      whois.wrapper: usr/bin/whois

apps:
  whois-snap:
    command: whois
    plugs: [network]
    
